[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
title = "Progressio's Alacritty"

[window.padding]
x = 5
y = 1

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

